# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd3ff681cdc4cfb4219cf4eea9385700271ac9ac0a599d507848cd736cc675ff074f81109dd2e60e5a7bb0fd5e49c25700770f5b7aaa8fd2b66d28f9f0777223

test:
  secret_key_base: 1bb5124a1e6756e3cbf80a19f615857bdcf2cd4a168f3b768df89c9a846730489036d451f7102fffcd24e5f7a6d510bc833365d4b58ddc838c79ad9f7498a35b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
